apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test1-ipallowlist
  namespace: test1
spec:
  ipAllowList:
    sourceRange:
      - 172.26.0.0/24
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test1-ingressroute-middleware
  namespace: test1
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`test3.ilba.cat`)
      kind: Rule
      services:
        - name: app-ilba-service
          namespace: test1
          port: 8080
      middlewares:
        - name: test1-ipallowlist
